### ISSUE TITLE
Not finding new secrets. Reporting as 'No secrets found'.

### ISSUE THREAD

**Issue by chetmancini** [Yelp/detect-secrets-server#29]
Hi I'm interested in getting `detect-secrets-server` tracking several of my repositories, but I can't seem to get it to actually report new secrets. I'm not sure if I'm doing something dumb or if I'm not following the right commands. Perhaps it's an easy fix and someone on the project can save me and others a bunch of time.

Here's my config
repos.yaml:
```
tracked:
  -   repo: git@github.com:Orgname/repo1.git
      storage: s3
  -   repo: git@github.com:Orgname/repo2.git
      storage: s3
```

s3.yaml:
```
credentials_filename: detect-secrets/creds.json
bucket_name: org.bucket.name
prefix: security-monitoring/detect-secrets-metadata/tracked_repos
```

I added repositories like this:
```
detect-secrets-server add --config detect-secrets/repos.yaml --s3-config detect-secrets/s3.yaml
```

Then I've setup a task (I'm running on Jenkins) run:
```
detect-secrets-server -v scan Orgname/repo1
detect-secrets-server -v scan Orgname/repo2
```
and I commit a new file to repo1, `test_security.py`:
```
SUPER_SECRET = 'bLwhhBqKqDfUypeXgzDeokMXdxjb'
A_PASSWORD = 'CXbwXy9gk/qivqR[p2u&f'
```
and then I rerun scans and get:
```
[scan]	INFO	No secrets found for Orgname/repo1
[scan]	INFO	No secrets found for Orgname/repo2
```

I've been trying to go through the code and figure what I'm doing wrong but everything so far has seemed normal. Thank you so much for any help!

**Comment by chetmancini** [comment]
Also I love giving back to good projects, so once I get this running I'd love to help contribute if there's need.

**Comment by akshayatplivo** [comment]
Have been facing the same issue as mentioned by @chetmancini ... have just been getting 

**[scan]	INFO	No secrets found for my-repo**

Detect-secrets seems to be working like a charm.. This however has been acting weird. 

Tried cloning the repo locally and scanning, that however works. 

Remote scan of git repos seems to be down and not working. Will be great if this is fixed as this is a major road block for server-side scanning. 

Thank you.

**Comment by KevinHock** [comment]
My deepest apologies for not looking at this sooner, will look at this soon. 👍

**Comment by akshayatplivo** [comment]
@KevinHock  Hey Kevin any luck on getting this up and running?  Hoping for a few +ve's

Thanks.

**Comment by rameshkumar-a** [comment]
@KevinHock , it will be great if this issue solved

**Comment by KevinHock** [comment]
I couldn't get to the bottom of it today, but I'll look into it more on Monday :) I've added the `important` tag.

**Comment by KevinHock** [comment]
#### The problem

I tracked it down, it is due to the way we [use fetch](https://github.com/Yelp/detect-secrets-server/blob/d69c9affcfcaec0597e1c3b68cd7959be0d96fde/detect_secrets_server/storage/core/git.py#L51), it only updates the `FETCH_HEAD` and not the `HEAD`.

#### How to fix

I am currently trying to decide whether or not to:

1. Change the [way we clone](https://github.com/Yelp/detect-secrets-server/blob/d69c9affcfcaec0597e1c3b68cd7959be0d96fde/detect_secrets_server/storage/core/git.py#L37) to use `--mirror` instead of just `--bare`, and use e.g. `git remote update`. This works and is simple! However, as [this awesome article](http://christoph.ruegg.name/blog/git-howto-mirror-a-github-repository-without-pull-refs.html) from @cdrnet shows, it fetches all remotes too, that we do not currently care about, so it is a little inefficient. i.e. [from the docs](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---mirror)
```Compared to --bare, --mirror not only maps local branches of the source to local branches of the target, it maps all refs (including remote-tracking branches, notes etc.) and sets up a refspec configuration such that all these refs are overwritten by a git remote update in the target repository.``` We could trim it down like in that article, though that may be a little involved.


Or 

2. Just reference the `FETCH_HEAD` in [`git.py`](https://github.com/Yelp/detect-secrets-server/blob/master/detect_secrets_server/storage/core/git.py), e.g.

```python
def get_diff(directory, last_commit_hash, use_fetch_head):
    """Returns the git diff between last commit hash, and either HEAD or FETCH_HEAD."""
    head_type = 'FETCH_HEAD' if use_fetch_head else 'HEAD'
    return _git(
        directory,
        'diff',
        last_commit_hash,
        head_type,
        '--',
        *_filter_filenames_from_diff(directory, last_commit_hash, head_type)
    )
```
This makes the code pretty ugly, aside from all the `use_fetch_head` `True` or `False` stuff, e.g. we would always need to fetch immediately after cloning, so that there would always be a `FETCH_HEAD` in the bare repo.


I will try to go for `1.`, and make a PR.

#### Historical context

We switched to `fetch` from `pull`  to fix issue https://github.com/Yelp/detect-secrets-server/issues/21, and didn't remember why we originally switched from `fetch` to `pull`. But once we fix this GitHub issue, hopefully we won't have any similar issues.🤞 

#### How do other secret scanner projects do this?

They do not mess around with bare repos, they just clone them normally.

- [`gitleaks`](https://github.com/zricethezav/gitleaks/blob/398366a6155bdc78bd1f206ffc217bcda4ac2a54/src/github.go#L188)
- [`gitrob`](https://github.com/michenriksen/gitrob/blob/d2f49019edb6fc992e8b28235c3bd8609ce5c39c/core/git.go#L24 )
- and [Trufflehog](https://github.com/dxa4481/truffleHog) does
```python
from git import Repo
...
def clone_git_repo(git_url):
    project_path = tempfile.mkdtemp()
    Repo.clone_from(git_url, project_path)
    return project_path
```

I could not find the clones in
- https://github.com/auth0/repo-supervisor
- https://github.com/UKHomeOffice/repo-security-scanner
- https://github.com/awslabs/git-secrets

**Comment by KevinHock** [comment]
So a quick fix for this, is for us to do `master:master` instead of just `master` when doing `git fetch origin master`. We knew to do this, but I didn't catch what the difference was. `master` updates `FETCH_HEAD` whereas `master:master` updates `HEAD`.

The [code location for this is here](https://github.com/Yelp/detect-secrets-server/blob/d69c9affcfcaec0597e1c3b68cd7959be0d96fde/detect_secrets_server/storage/core/git.py#L57).

The downside of this is it silently fails when the remote deviates from the local, i.e. it doesn't update anything. So doing `--mirror` and `git remote update` like above may be an improvement. I'll release a new version tomorrow with the short-term fix, i.e. do `master:master`.

**Comment by chetmancini** [comment]
This explains a lot--thank you for investigating!

**Comment by akshayatplivo** [comment]
@KevinHock  Thank you Kevin... Awaiting the fix :)

**Comment by KevinHock** [comment]
re:
>The downside of this is it silently fails when the remote deviates from the local, i.e. it doesn't update anything. So doing --mirror and git remote update like above may be an improvement. I'll release a new version tomorrow with the short-term fix, i.e. do master:master.

Doing `--force` worked fine for this purpose, so I added it to #30.

**Comment by KevinHock** [comment]
Okay, [just bumped the version](https://github.com/Yelp/detect-secrets-server/blob/master/CHANGELOG.md#0212) to `0.2.12`, it should be available via `pip` in a few minutes.

Thanks all, sorry this took so long, feel free to make another issue if you run into any issues.

**Comment by akshayatplivo** [comment]
@KevinHock This is fantastic!! Thank you... Will be testing this today.. Will post my updates.

**Comment by rameshkumar-a** [comment]
@KevinHock  it working fine for me ,thanks lot for your support

**Comment by akshayatplivo** [comment]
@KevinHock Working fine for me.. Thanks a lot for the quick fix. Cheers.
