### ISSUE TITLE
First Scan failed to detect the secrets

### ISSUE THREAD

**Issue by rameshkumar-a** [Yelp/detect-secrets-server#31]
Hi Team ,
  Steps to replicate the issue 

1) I have added the secrets in Repository test_data_valiate.py
  Content : 'd1bc8d3ba4afc7e109612cb73acbdddac052c93025aa1f82942edabb7deb82a1'
2) detect-secrets-server add git@github.com:org-name/projectname
3) detect-secrets-server -v scan org-name/projectname
Actual Result :   [scan]  INFO    No secrets found for org-name/projectname
Expected result : [scan]  ERROR   Secrets found in org-name/projectname

When i add the same file again and scan the repository it's working perfectly 

Only on First scan it's failing .

Please advise i need add any new parameter here.

**Comment by KevinHock** [comment]
Hi @rameshkumar-a,

This is by design actually, the `detect-secrets-server` is for "from now on" detection, whereas the standalone [`detect-secrets`](https://github.com/Yelp/detect-secrets) tool is for scanning the secrets currently in the codebase.

[This blogpost](https://engineeringblog.yelp.com/2018/06/yelps-secret-detector.html) from @domanchi might elaborate more.

In your example, if you add secrets to the repository after step 2 (`add` ing the repo), `detect-secrets-server` should alert.

What `add` does is save the current HEAD in a repo metadata file, and then `scan` fetches new changes, and diffs the hash in the metadata file with the current HEAD after fetching. So in your example since you're scanning right after adding, it'll `fetch`, see no updates, and diff HEAD and HEAD.

**Comment by domanchi** [comment]
Also relevant: https://github.com/Yelp/detect-secrets-server/issues/9

**Comment by rameshkumar-a** [comment]
@KevinHock  @domanchi thanks for the quick feedback, closing the issue
