### ISSUE TITLE
Scan every branch at once

### ISSUE THREAD

**Issue by equals215** [Yelp/detect-secrets-server#38]
Hi,
I'm using detect-secrets-server for an enterprise grade project and I was wondering if detect-secrets-server was capable of scanning every commit, if not, every branch for secrets and not only HEAD or a specific ref ?

**Comment by domanchi** [comment]
@equals215 : not at its current state.

We scan the master branch, because there's only one source of truth for code. Assuming that other branches will either eventually:

1. Fork off into a different repo
2. Merge into master

We can handle both cases with scanning the master branch.

On this master branch, we technically scan every commit by scanning the diffs between the last known good state, and the current HEAD.

There's a clear and important distinction between tools like `truffleHog` and `detect-secrets`. The former scours a repository to find secrets (looking through many different avenues) while the latter attempts to ensure that secrets are not committed to the codebase (or quickly alerts if it does). There are inherent design trade-offs between the two philosophies/approaches. You just need to decide which use case fits best for you.

**Comment by equals215** [comment]
Thanks for your detailed response domanchi, I think truffleHog is better suited to my needs than detect-secrets-server but it seriously lacks configuration.
Have a nice day !
