### ISSUE TITLE
Not able to scan branches

### ISSUE THREAD

**Issue by ram2valar** [Yelp/detect-secrets-server#53]
Hi Team,

We are having our private git configured in our infrastructure. We are able to perform scan using detect-secrets only on the master branch i.e. head.

2004 # detect-secrets-server -v scan https://gitlab.devops/devops-infra/devops-interview
Username for 'https://gitlab.devops': admin
Password for 'https://admin@gitlab.devops':
Secrets found in devops-infra/devops-interview
{"repo": "devops-infra/devops-interview", "output": {"textfile": [{"line_number": 3, "author": "admin", "is_verified": false, "hashed_secret": "df4f6cdba08513e1b5634f166d6cb152d31aedf6", "commit": "faea6caeb8b94f88da196ac69aeb66a14c0d0912", "type": "Secret Keyword"}]}}

we are not able to scan the repos which has multiple branches and feature branch. Is this tool wont support scanning on child branches?

When we have above textfile in develop branch, without merging to Head i.e. master if we perform scan, no results. Does it implies only Head i.e master branch can be scanned.

When we clone the repo to developer's local desktop and perform scanning its giving result.

How can we achieve scanning of multiple branches of repos before merging to master. We dont have command line arguments to specify the branch while scanning.

Thanks,
DevOps Enthusiasist.

**Comment by domanchi** [comment]
Hi @ram2valar,

Yes, that's accurate that only the `master` branch is supported for file scanning. This is in line with the spirit of the tool: to find newly created secrets that have already been committed to the code base.

Since feature branches will eventually end up on the `master` branch, this tool will eventually catch it. If you wanted a quicker deterrent, I suggest you use our [detect-secrets](https://github.com/Yelp/detect-secrets) tool instead.

**Comment by ram2valar** [comment]
@domanchi Thanks for the confirmation. Yes we will use this tool by cloning the branch as well as we will insist developer to use to scan their code-base too. Upfront we will enable this for the master branch of the repo.
