### ISSUE TITLE
is Hashed_secret unique?

### ISSUE THREAD

**Issue by opt9** [Yelp/detect-secrets-server#60]
I want to store the scanning result to the db and, i'm considering to use `hashed_secret` as a primary key.
Is `hashed_secret` uniq?

**Comment by OiCMudkips** [comment]
Hey, `hashed_secret` is a [SHA1](https://github.com/Yelp/detect-secrets/blob/0e8925d685f1fe34a1e315045450cd678104648c/detect_secrets/core/potential_secret.py#L80) of the string detected as a secret. If the same secret appears twice in the same/a different file, they will have the same hash.

Otherwise, different secrets will result in different `hashed_secret`s. If you find a collision, please let the wider internet know as you've found a SHA1 collision :)
